name: connectivity_web
description: An implementation for the web platform of the Flutter `connectivity` plugin. This uses the browser's NetworkInformation Web API through Dart's JS interop. Due to privacy concerns, not all features available to Mobile apps are available to Web apps.
version: 0.1.0
homepage: https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ConnectivityPlugin
        fileName: connectivity_web.dart

dependencies:
  connectivity_platform_interface: ^1.0.3
  js: ^0.6.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"
