name: connectivity_example
description: Demonstrates how to use the connectivity plugin.

dependencies:
  flutter:
    sdk: flutter
  connectivity:
    path: ../
  connectivity_web:
    path: ../../connectivity_web

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0

flutter:
  uses-material-design: true
